# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\".\n\x08LoginReq\x12\x15\n\x08username\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_username\";\n\x0bUserSession\x12\x1a\n\rsession_token\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_session_token\"\x07\n\x05\x45mpty\"X\n\x04Item\x12\x0f\n\x02id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x12\n\x05price\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\x11\n\x04name\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x05\n\x03_idB\x08\n\x06_priceB\x07\n\x05_name\"\x15\n\x13GetUserInventoryReq\"\x0e\n\x0cItemsListReq\"\x0c\n\nBuyItemReq\"f\n\x08UserData\x12\x15\n\x08username\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x63redits\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x14\n\x05items\x18\x03 \x03(\x0b\x32\x05.ItemB\x0b\n\t_usernameB\n\n\x08_credits\"!\n\tItemsList\x12\x14\n\x05items\x18\x01 \x03(\x0b\x32\x05.Item2*\n\x04\x41uth\x12\"\n\x05Login\x12\t.LoginReq\x1a\x0c.UserSession\"\x00\x32\x90\x01\n\x04Meta\x12\x1c\n\x05Login\x12\x06.Empty\x1a\t.UserData\"\x00\x12\"\n\x0bGetUserData\x12\x06.Empty\x1a\t.UserData\"\x00\x12$\n\x0cGetShopItems\x12\x06.Empty\x1a\n.ItemsList\"\x00\x12 \n\x07\x42uyItem\x12\x0b.BuyItemReq\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQ']._serialized_start=13
  _globals['_LOGINREQ']._serialized_end=59
  _globals['_USERSESSION']._serialized_start=61
  _globals['_USERSESSION']._serialized_end=120
  _globals['_EMPTY']._serialized_start=122
  _globals['_EMPTY']._serialized_end=129
  _globals['_ITEM']._serialized_start=131
  _globals['_ITEM']._serialized_end=219
  _globals['_GETUSERINVENTORYREQ']._serialized_start=221
  _globals['_GETUSERINVENTORYREQ']._serialized_end=242
  _globals['_ITEMSLISTREQ']._serialized_start=244
  _globals['_ITEMSLISTREQ']._serialized_end=258
  _globals['_BUYITEMREQ']._serialized_start=260
  _globals['_BUYITEMREQ']._serialized_end=272
  _globals['_USERDATA']._serialized_start=274
  _globals['_USERDATA']._serialized_end=376
  _globals['_ITEMSLIST']._serialized_start=378
  _globals['_ITEMSLIST']._serialized_end=411
  _globals['_AUTH']._serialized_start=413
  _globals['_AUTH']._serialized_end=455
  _globals['_META']._serialized_start=458
  _globals['_META']._serialized_end=602
# @@protoc_insertion_point(module_scope)
