# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n\x0bRegisterReq\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1c\n\x08LoginReq\x12\x10\n\x08username\x18\x01 \x01(\t\"$\n\x0bUserSession\x12\x15\n\rsession_token\x18\x01 \x01(\t\"\x15\n\x13GetUserInventoryReq\"\x0e\n\x0cItemsListReq\"\x0c\n\nBuyItemReq\"\x0f\n\rUserInventory\"\x0b\n\tItemsList\"\x1a\n\x07\x45\x63hoReq\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08\x45\x63hoResp\x12\x0f\n\x07message\x18\x01 \x01(\t2T\n\x04\x41uth\x12(\n\x08Register\x12\x0c.RegisterReq\x1a\x0c.UserSession\"\x00\x12\"\n\x05Login\x12\t.LoginReq\x1a\x0c.UserSession\"\x00\x32\xcb\x01\n\x04Meta\x12\x1d\n\x04\x45\x63ho\x12\x08.EchoReq\x1a\t.EchoResp\"\x00\x12<\n\x10GetUserInventory\x12\x16.google.protobuf.Empty\x1a\x0e.UserInventory\"\x00\x12\x34\n\x0cGetItemsList\x12\x16.google.protobuf.Empty\x1a\n.ItemsList\"\x00\x12\x30\n\x07\x42uyItem\x12\x0b.BuyItemReq\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQ']._serialized_start=42
  _globals['_REGISTERREQ']._serialized_end=73
  _globals['_LOGINREQ']._serialized_start=75
  _globals['_LOGINREQ']._serialized_end=103
  _globals['_USERSESSION']._serialized_start=105
  _globals['_USERSESSION']._serialized_end=141
  _globals['_GETUSERINVENTORYREQ']._serialized_start=143
  _globals['_GETUSERINVENTORYREQ']._serialized_end=164
  _globals['_ITEMSLISTREQ']._serialized_start=166
  _globals['_ITEMSLISTREQ']._serialized_end=180
  _globals['_BUYITEMREQ']._serialized_start=182
  _globals['_BUYITEMREQ']._serialized_end=194
  _globals['_USERINVENTORY']._serialized_start=196
  _globals['_USERINVENTORY']._serialized_end=211
  _globals['_ITEMSLIST']._serialized_start=213
  _globals['_ITEMSLIST']._serialized_end=224
  _globals['_ECHOREQ']._serialized_start=226
  _globals['_ECHOREQ']._serialized_end=252
  _globals['_ECHORESP']._serialized_start=254
  _globals['_ECHORESP']._serialized_end=281
  _globals['_AUTH']._serialized_start=283
  _globals['_AUTH']._serialized_end=367
  _globals['_META']._serialized_start=370
  _globals['_META']._serialized_end=573
# @@protoc_insertion_point(module_scope)
